[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "948ae075b25017d408224e6f67003ce9f072b5a9"
os = "macos"

    [[MPFR.download]]
    sha256 = "d2b24adc1e0412d9eaa36eefc443686b38a77d92b22ea3ec95eb8ce569066990"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "c510e3668600d89b4d769bf6ea59e7e65e58e82e"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "7f3af61e09e43872831191c0d438c77b96581f67c51f5468efbdc1c52aa9ad3b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "91ce82a0d4b966298b843707795cedfef07fb736"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "ba8d8916289bc5f83b2eec56b385d7a8cb2e17b571241e78ef0823f85c725834"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec8e9f7d806745755661eaf6d3390b788f04fdda"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "9e5a4b247187b15d89f51272b17c6fd6d70d6fca4859be9fe84321ffaa86965b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "125b9d3c8f55ce08c02de8e4a5f5127c131ae7c5"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "296d4693f0e78cdbf8adcd5751c18c619245a565f05e6091749fea4dca35485e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f3f34e3fd82a2a882caf4a98948ed09df94e28d"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "a94fb7b89bd716208e49941d997ec0b74568b1e67a8759a0b2ddbec334c1e52e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abeb6b0c1fce6069570a3e40ec9887630e6c0d7a"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "8d5752368c7a0a1be3926d16880bede86ced9189516715add8648026767e413d"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "48c15bbef43d8a498b8e61521ce1ee550d1a0f7c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "1aa52576579efe55d2f9752df0b419ad2dd65e361b679ec27259583f6729d463"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "8bd3fbc972363da29699d5c39fdd4dfa9cc6223d"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "983cf297a6a2e0217bf39e3f2e3e3a12a9e15fd804641869cf0440969f0c7881"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "22f58dfe8f4b9ae95f693eec7fe1a93d3d593c9c"
os = "windows"

    [[MPFR.download]]
    sha256 = "13bac3922d097f7af4bc17a46d2420a4ed2d7a44d27a5869abf51eb2dfa04e5e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "ad8a9029305016903f4de018e0e8e9a647041377"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "6489ad1b214e289303ba061dff6082e750ba93ce703dbc6d0fc8043ce89c204e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "f9bc618afeeabd338e9b41935cda941fdb753e1e"
os = "macos"

    [[MPFR.download]]
    sha256 = "d39e3e942f890f3225a9f5eb943ad6f8e40d9755ab56f180d8f356432d739605"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "a834899847b3147120dbea8e037c285c49dfe969"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "4b15f32f0e949f928bebdb326a7b70b95c470270a48241921858f4a5014225cc"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "cda78e622a131a1f5a387239ce3264574894cbb9"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "bb2d71a1d54524ab59fec8f2f4d86f358cbbad2a65c223574878c64c7a935ee1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "4dd501fcc5eb52d588c71253ff8fc5cb7946d891"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "0d5eb2b8d1e82738c7a24e3718d93500a81245080a88ca99292aa8815466aa78"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "44d1c8644d87550992d6fd741e28c0aec4d5e759"
os = "windows"

    [[MPFR.download]]
    sha256 = "7619633aff58e6d7088467770934872ffeac905fdd5f90ec47c0e31218101b89"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+0/MPFR.v4.1.1.x86_64-w64-mingw32.tar.gz"
