[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "e0f4f3ac2100b4f03766f9409d16bf6c6ed9d14c"
os = "macos"

    [[MPFR.download]]
    sha256 = "224d4264a66f793f7371127bac1d28f3d23d8c06275d30142bd5e0729c026453"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "ef964440906e2b6fc82bdf81d82e62e20be183bc"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "0258c464c8fdf0548a5044f23de5a87ebcc635d46dcd0dc72c7416df90a23c34"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "93f29125328772872b6c9076faf341669affe743"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "eb4a65aa3a097b5d5eb9a9a7034b79194c973d3014a89f287a6b3bec810d6dcf"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "9a109bdcfd2b9139baf8ef844439c97f9510dc08"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "9df2a1d78e26a01a7d7d7bf08e8d1b25af09e9f56f79f98d568d666d0bcb736d"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.aarch64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d39e1208ed9fbb4045894b68890c556a249bcfe5"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "bf3c3a8b66b4f4ec7b877a84dad49f2e4dc0096c3b4f1beb634fb396f9270117"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5ea77f520f6e3265234ab9131a305095189bc96"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "5f1918c67962bc6f436f27b85664c1281f6f21f8066c514bc8912b59a7744c72"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44757b4e056c66c2488207e15c004203d64548db"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "e7f4dfe9f1afd3994ac4897f4d95dc74f67cca2b76e01beecda5cf140c317589"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b05d3cb53efee998555df7292a27568cd6c189e"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "b834bc5858e46a79be2f32dc1c532a1ef3c3d399d32f1c817108e930f81731bf"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "7e234f0f184dde14d50b8e758fc35800b4b351d9"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "45e9b7f7b5bdc1dbc859579f7c6b78b72ffac122f486b2ecdd52ce7bae009801"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "77c180f422274fae55caad4351a3ccac1221509e"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "430f5fec3d218f662b30eb1fc5234dda84694bbef786555bed7291d9de9ffdfc"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "421bf77d9b706b8eb00322c2e3efaf472f5d7784"
os = "windows"

    [[MPFR.download]]
    sha256 = "ec3deee628735d922308b9228fa75637c45cdf443a8a42858b8c26555a1b1c37"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "6c267274da7f83b59a192b1f6351bf7347b2bdee"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "5ba5cb042a9542143219d6adf37ff4f56a70333dd1f740e4630dafddd1a9458b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "riscv64"
git-tree-sha1 = "1ea50c0b17603660c1c6660ad6b240a49e88ac16"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "006e357d1ce9446adec25167d598509fd3e810eaac319eedc7db1c136caccbc0"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.riscv64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "ae0c7bb07028e824ba58b8d39addedce1f7e82ce"
os = "macos"

    [[MPFR.download]]
    sha256 = "f72dbfb1423299f16438762ee17cbc0cff77c402da5bb9c17a11f062db3ce7ce"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "480d998616302177a73f3e64a4b2933bf6ef5e6a"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "cc975e875b891dd98350e96c23dc9996c521219817c982184ad3256c4fa538c6"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "5a3ef65add5f31cfb7e224386ca08f89855c4171"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[MPFR.download]]
    sha256 = "6da6f62d840755bdab1cd76008c247ed95ed18fc0bb1027427a6e39a1a05c1c8"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "05ad7edebb3c42d82c0305578e56d66ad38322b8"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "e7ab27ef6bc2f5e0bfa85755bd6ddb39443c3334becbab672cd8afa1ab84b88d"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "d293404e616f824eba8a7731a01ca117dd83dd86"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "a0ddaec10927c7902b0134330c4835d80be1408f93b49a24d37511d4fd0816b8"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "7c5cce891af48e0fe34c74d95a4a054ab60007b5"
os = "windows"

    [[MPFR.download]]
    sha256 = "e29439a659f5a87505f1d9047aa2d4f18aa5e9ad7e8ecea32a48059b30d8b740"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+6/MPFR.v4.1.1.x86_64-w64-mingw32.tar.gz"
