[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "babc6be3a2134336f2731fc9974b8ef45d68f304"
os = "macos"

    [[MPFR.download]]
    sha256 = "8408c4278191d448af67da3877c24e2e667d01b88ac0dba70aa29923a0846dc2"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "463c4b09e28cba1983a4c39bc54051bfa68098d5"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "d502a76ddb6eb313677f9d159ec551a9632bdbbc52c7b489dc6a9e35cf85b613"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "5f62d9218f8361bc5d56a76e208e8838ef639a6d"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "8409c89ab5695ceb2c2d9a48ca1b9a707df9db77094187414bddd85326de492b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a40f2024d0713784fb4cbd3d8678a7a9589a403c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "7fcaf7ea27f2d7098550f01547ca7d57ab6af751db0d81b7d21f0d1ce1d4bfdb"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4b35975896e02e62bcce4bce77125b41e2c143e2"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "f7546d8ac0195f34778a269bb84c6a80a7ab39281ee98b6ac4cf976088b03cf3"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3fdffdab393a860f7cb93bd6f5c822fb372d8378"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "cfc4c5d80f5f7dcb18bab531ad4c1832233f08bc5173a6d978c04d2a8bde46b3"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d5b11c76f097160a7a7dbbedb7390d64ca460725"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "8f28e09226f36cd4a17bfb4c03fbd6c3bf780cdc1f4289dda6128a5d7fe49584"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "41b3d9b2aadf457ed98746e49785b54791d567d4"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "386e8a79e8bd9635c3517a9272c8f34330d66abae3bb48bd8153e8c76f60358f"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "2a47246a8547dbde4de389d44055a75b810578c4"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "78ba5a192bf39f2a31603430e6b73c468de35735e76c320c8e5d1bea7d6253d7"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "b9825d377bda8063cad5e9c16f4b7d8f829a626b"
os = "windows"

    [[MPFR.download]]
    sha256 = "934d7401583d23fe02317da9882531b55519020f9cc9fea074bcbd58af4aa9f7"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "9b2e54e7ab5ff1f15ecebc29f849ddec96805a5e"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "1030a60e3af478ee5a7fd3675656fafbd178b5e87d6e1ed71bc02fcb7378b350"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "9fb31a48997125cee02464cf76acf6b941468c94"
os = "macos"

    [[MPFR.download]]
    sha256 = "6e3998f39b8f75ac13cce7dbfa8aec914b4f36788473a4fefc1ae217838fe81b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "46c056c112c02d76f4e374b3d4df2bf2939bf02c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "e9f2c742a5c105ef6e68e57f35967a0fcdd7822c75f00c1568093a632d1c7a55"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "ada8288e24f6fa0d52a884dfcbdde516e62b5ca6"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "7e9bac33e1354b7d262a0e03fd90c5cfb553fa22c6eade6887bfc105c21aea7c"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "920a7d385a9134875c256ab73e3b93e9fdd27a53"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "5721f2ea8c89bd075ce55e90e5e2841656c22a3ade986464b541f412c1a03f2f"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "151f2eddd880ed7c63f6ef44214af079c54268e0"
os = "windows"

    [[MPFR.download]]
    sha256 = "db89e05280774b388ee3180d519a8239cb401e6bb3eb56705de713ec03839cdc"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+2/MPFR.v4.1.1.x86_64-w64-mingw32.tar.gz"
