[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "0d62ea87898fb65f863653c34a904624ecdc0802"
os = "macos"

    [[MPFR.download]]
    sha256 = "cd32b71e87d697c28be4d605a39a04aa3ec0a5ca5f5c23e0bfb7a672bea799c1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "a0dde9dfef264ba245e121997740ca0b8c85a08b"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "789d093ec5cfd798fdadb2dd31c14fbeee8c0df28452e45830ce3fab11e95951"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "100158e4ec276c7d2992c6835dd21abc70f26e5c"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "d714b7f52a4e96c88f710eea774b4ff5bf57621033af8013a4a8f5ac24abe160"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "51a7b9e1397a9413190c570b9769cffe3b18822c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "94fc07b02a0d945bf18446e9483f2521258de68660160906134d2d2d76261265"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "204d28da44a1396b24c8f28848a22397433d76cb"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "bf5d0c1a649b439acb1eedd3ee1e4fe489e162d985da2ea0b35ac6d1ff181943"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cbcd0809d1dbaf4d79edbe2965a5412bf90c91c3"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "b9c14a26628e63e354e29e0e97f4b299b34fe697dd3e9c64c6c5979a2f820d3a"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "449c77e82c7e6cc2053b7e0c7ddb03c407edd58c"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "becda700e16a1d68d32df8a3a6e5dcfb6e3484016645858610b417315bae9f91"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "50aa7153365466229f2ed75192cb35b647847cb5"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "f744f10bad2cb2cd0904583af3b23cbee11c1ff9e1967fcf2757ad1b12febc5f"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "bcc8ec4bcb64f7a9f86efc08ecee22e3ba41d5f0"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "3d24a77683c6faf1ad775577e3b42e06a60a860239d65d57d71bf6e265640232"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "6ebe6381e58f02d3390fab7236c1ad58a89cf7e9"
os = "windows"

    [[MPFR.download]]
    sha256 = "7c4b68107033e7b494821c4309d0bebda645396957ca393b5e119dbeaf3aa783"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "98317f1b06cb64a4f1f3cee53bed9c16ea979d12"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "bd3b42c030c6d36f5bc83d3ca8ea414ab214e14f986187f9737920b92af2065a"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "049c111cbbbbca9c7d7b5d60911401b2809056a1"
os = "macos"

    [[MPFR.download]]
    sha256 = "44b5508a1db4065a7a0e72c964e208d6705141a958a7911b955e834bf9ddd0d6"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "5f30672c17afb8ec61558a3b8fbeba51c9a00945"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "7c1661c7b345c27dbaa799efb166976aa5c173c3dc93b975bf8a16ac27d64b63"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "932bbb52eb1fb430274ff7788645e19c6ff18fee"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "47d3836c4581aa421adcb3dd5f5b52ee025503491f08ec22e469517587f3ddb1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "ece5b7fa490a2c44769624ec4dffb29185c2b66c"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "9c61f0b82e210f54098aa1056a13b61063ddbd21134897529abf0495e889bbec"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "e1d12256a84e2a56907f1594b303239b10956386"
os = "windows"

    [[MPFR.download]]
    sha256 = "497acdcb53a6b832844b93dc6e31cae66eeda64a70a51dba5eaff6fa0fb7bb5a"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+1/MPFR.v4.1.1.x86_64-w64-mingw32.tar.gz"
