[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "4cb2c3604820c1240bdf1202e80b7c27333e7b66"
os = "macos"

    [[MPFR.download]]
    sha256 = "5f8c25ce20fc37b616b1a82a737b1de3ef1f8e8a59661f1279fefbdddfda0bca"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "5e743fcaec9ec58333bdadd03d792104554cee8f"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "8c469eda11f3f56e525efcc8918ddcd2f60ea3011aa84ada84b970eb2e71355b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "827708ffc19fc20308da43a9b5051c1c5ceeb34e"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "4b8dec03657d32e02edf0c0badc8b0465581961c61e191560406baf42eea213d"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "e9750b5e71cba15cb9695c4f6e0bd70efccd5787"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "6f291a7e542ba3d0c85adafa06ac1f64a78e58a1084c2b9413b54d61c6b19f7e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.aarch64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4064ea1137686412a323400daaae5bbd6aae31e1"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "2da26e190c1e0afd8f1cbe92efcb782a27c66a7bfbd2f6e28a2d75b2399338cb"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82fcc168a9d3977baf363d2c5afcecacefcc0e1a"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "eeaa91304d4cf8eaeecee3d80b18ca4d83ab3363932e388388230a62d841cf5e"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36118a199b1d66569240c9196e3a737a8916141c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "c8086d3f076ae38eb32e3ee2dd0a5cd681deca4b120eedda7b0c01ce691bf241"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2dd83ecc6b64d40bdda0c820dc9d468c3009aea3"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "5b17b8f07094dafbea8f9ea01904e3e5e63e231f173ed18469df7a9756ddcafc"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "91340b74118eaab7b6d3e5eeb4fff62724f10f60"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "b890253ff5ba8f08f8bfbc47a71d3d08ae7e440272e75f760c7910f4892f2c85"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "a397edf57cc33019527977aa07d5a40c6c2f5ed4"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "b36f088b3bd18860ce985737c99a45025fec0664ecea753e15abe5f430e402b3"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "420c166700cc2ccbdafc2457c342ed1bed045c76"
os = "windows"

    [[MPFR.download]]
    sha256 = "2fe789887296d31eb621c83f13d2dc8bd21ac2bced63c3787cc5dd50863863ab"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "9e2059d213a4d75a3cd40e4027dc897f96b0e22e"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "568ef05e08f9d080177230152c55a9ce16bafbdfb46954d89551a5174454a343"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "d40c765e0cc94c901c85a9afdaa73c87c5d899d0"
os = "macos"

    [[MPFR.download]]
    sha256 = "de89412ae7740bd8f5af713bf0e91323ec7f789c1b7de56291e5af4c4e57309f"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "109a360e8e928deab943b64ac3bd092bcff0d8cc"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "755e2657f0981b80d2de4016e52494536fee4a8bfb2814477393ca4ec053ab36"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "7db1ddb46ac3e0a4186e3aa9cbec9d068472cd38"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[MPFR.download]]
    sha256 = "523cd3fd4ed90758f39e2ef638deb1ae9ec0949b3fad72f9d2b726a53176c1ad"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "72fe54c5e52463058bd42cf1c9de82aeb2f8049a"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "20d7c78251b2f42670845c91fe161c2995bc79691c8f19cb47481e27fb8fb826"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "de663741f76e01429d2c5ba7f21729192f00a1c7"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "8096606a3413b69a3db53b3a312d043ff834f2c11aedf6253fb87b61a264d93f"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "2b354a861e1ba91614cbe59ab73af0559c8cccc3"
os = "windows"

    [[MPFR.download]]
    sha256 = "34d58d27c0bb3b45c0b5190b8a0743ecc5e3666e76d423a7a68bb5cc5b805d3c"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.1+5/MPFR.v4.1.1.x86_64-w64-mingw32.tar.gz"
