[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "8adc35231b3547cea4d3284958c2714e6618cb58"
os = "macos"

    [[MPFR.download]]
    sha256 = "97f74d71cfdd76d47b93ed3bb155dae5b4e1e079f4a89d7532541af3a3b5a1b4"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.aarch64-apple-darwin.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "1f5ebe733b4502634670d7780b07b89bb90961f4"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "b990c91ff44be1d2c956b1186b336b845a788de6fc7e2ce7322a5fe84fce3937"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "68b83e1eac8b635d90d9aa0b1d5dbce9063e81dd"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "625b6d9271e1dab9a13e772103bbebef5bfdeea9712920a046cfe2dd220c877c"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "91d5d8520cfd670167dc07fa74c60f9333d94f60"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "d00e5e023b8c478f3ee1d3c79778b777f29c373782f10116e7e8e137cfe11ed1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.aarch64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d9eeffde91ad2a7b1225b691bac7315a9d822f0d"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "77cef4ab529b46d5bde2cbb9b06e89264a8e5f48e493fc677e6f19d1dc37f1f6"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.armv6l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4c995295ce0bc69feaf315793eea352b4cda97b4"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "4a5c7c97680555454acd5ffbfb7bb708286b79fbb054d3d766f0bc08d6d173b6"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.armv6l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc5ceb6722d72f97a83297a0e3352d6ee998a73d"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "52e0f59ee13bc8a01e0ae2aa4cd382f506dfac8e29c06a63e0d6ef7d9167c50d"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3bcbdf99b1729c2fbe735c7875ec00229c1b4be6"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "f886b073a7041c9b445fc62c129e609cf19541dbefa10514890377c209587ba1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "5701af39c44794a6254ddd65e93d200c2e62d45d"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "c2323868d34b734df5437cec4efcbf5440c0c2b850568ba0b30d5b023a03d34c"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "afa8c5baa1a58c9ede1cfc407057706280032cb9"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "fee688e880c9bc47c6c0810eb2208e211c30da55cf81af43554fa4d44ff324e8"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "fd8d33149fd33e19ead72a2479478fbd9b1b1b84"
os = "windows"

    [[MPFR.download]]
    sha256 = "aaf43a8f55696568962df787b35515592859708955a59b954c90bea2362e42fb"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "51bdc19b35c7c1f6fb886070948ec8ec33f0a20f"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "b68a936d1d79d1b140e4ec1b2f664d10c95e95441997660c181ae245e5b411b8"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "riscv64"
git-tree-sha1 = "b2efc04c2e64fe11c78187aa03237f248fc7e91c"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "273239d9b337415f421d4b2feacf36ece161df388e7f27420590e80d0c49351a"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.riscv64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "85b6d8163a535720c088fa9a4da375be5b90e49c"
os = "macos"

    [[MPFR.download]]
    sha256 = "0f9d9d476c56a5a02bdd4155f08a98b4d3bf4215fa1a4eab9d175babfd4e08a3"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-apple-darwin.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "e55294399c993519e891a83b9a7dcd3ba51bd00e"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "11df4fac0ff9a8d61809146d8d906779eba02766ff6b5a4acd613336d8d36533"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "b6eb702f4b4c904639d8cb05f464c6c33ad57a24"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[MPFR.download]]
    sha256 = "492fdfb89e8be9da50bdb7d867045e6e2a1bf176c0694892f08aef55fcdfccaa"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "de5dff3abb0393e0544a023781c84f271a62ce0a"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "e19aab0f4adde2eb35da6a1aed125e4a33a53bc4b033b1e3ba1f1370b58dc3dd"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "eced7fc23b69c6c40a521e45cc90f50b430123c1"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "e13dc5dc1d5958cb3db58f6d14400244f84c6aab066b31aabc76a0531e386807"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-unknown-freebsd.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "f1f1f9d6d2d4947fd255fd1d4c65b570afee9da0"
os = "windows"

    [[MPFR.download]]
    sha256 = "a1b02dbd84237633b621d7480265b46dbe92ba9314cc88d478b0081a64cea06b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.2.0+2/MPFR.v4.2.0.x86_64-w64-mingw32.tar.gz"
