[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "adc037ec53cd98a43e2e7c7f605ec3acce150849"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "78961e85a1f322c799278452cf286c8d061fab0f7d2d20257e11236e4db0c443"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.aarch64-linux-gnu.tar.gz"
[[MPFR]]
arch = "aarch64"
git-tree-sha1 = "d089350eefa51631038b7cd66b03b21d5a5996b6"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "84c5402aa34e93b8985e0c8b7b5adf85063f85f26cf5916fa59388bd15434b44"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.aarch64-linux-musl.tar.gz"
[[MPFR]]
arch = "armv7l"
git-tree-sha1 = "1674e4daf680bc2d7708c4c716f149d0e5bdd425"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "7b2148013ae5280a211c1178f657e9f23d61e39cb8eedcac4737cddfc4bfa085"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[MPFR]]
arch = "armv7l"
git-tree-sha1 = "7cc3d2d535fa4654e8f475780a5f050ecab1b37d"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "466d5c6c3f277967687041ffcd30d6f2dfe855dd1e1e41780df5f2296b91c2f2"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "65b92573ad102b38603133dce45fdf75f40a4b4e"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "b833aa4cbf19b4cdaa45b91276f9d25b537b631c526b649fad15efeb4465f9b9"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.i686-linux-gnu.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "97947413cf82ba146991d8dc1ebd9cdf00b472b5"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "a867125d4a7011db31344bab1c8df69d614d4d797a64da774d0da9d56f3a2405"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.i686-linux-musl.tar.gz"
[[MPFR]]
arch = "i686"
git-tree-sha1 = "a04469c66b6306aa94796723ffb12d43f50ef01e"
os = "windows"

    [[MPFR.download]]
    sha256 = "960408f0b343bc749b30231f836bdc5c3961963b96e4b43dedfd6a3ce407e1de"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.i686-w64-mingw32.tar.gz"
[[MPFR]]
arch = "powerpc64le"
git-tree-sha1 = "5bc61bf8347ab48bd8c93dd0db1aab73d8a87ac7"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "3d23328a2854c677118e68868ce48a4932d5f97d40cdee1556a0a8ec55526830"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "6ccfdb924f1aedc7c5b0f45d71738abf648c6ee1"
os = "macos"

    [[MPFR.download]]
    sha256 = "0030db330ab0e82d04e4933e3aaeed5c3d261669725e26aed59bea5357f10daf"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.x86_64-apple-darwin14.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "15161b1e477174d02259bb32c1e3697c1cb506be"
libc = "glibc"
os = "linux"

    [[MPFR.download]]
    sha256 = "eebf0360156488d59050907aea9bb17ac3f5957e4404473eed662e4f547405eb"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.x86_64-linux-gnu.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "73f53c0ab12f79f24a789217a656e3a523906736"
libc = "musl"
os = "linux"

    [[MPFR.download]]
    sha256 = "9f2412902108b8a9ca50607e211f00d25fd2c89313345d2ba380b11a426868e1"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.x86_64-linux-musl.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "075d516095e650d916953a215a77324ed0a1f315"
os = "freebsd"

    [[MPFR.download]]
    sha256 = "9e3c3c2479a9c67bcbf7925e71f827643738a4ba4da54b93966ff9657e1e562b"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[MPFR]]
arch = "x86_64"
git-tree-sha1 = "196b73fe71fc09d4409c55c6c304369f38fdea99"
os = "windows"

    [[MPFR.download]]
    sha256 = "02898b13e6adf07ced8a0e443fed7e13c6cb8066a77fe51d4201b35f81cc4e34"
    url = "https://github.com/JuliaBinaryWrappers/MPFR_jll.jl/releases/download/MPFR-v4.1.0+1/MPFR.v4.1.0.x86_64-w64-mingw32.tar.gz"
