# Autogenerated wrapper script for MPFR_jll for i686-linux-musl
export libmpfr

using GMP_jll
JLLWrappers.@generate_wrapper_header("MPFR")
JLLWrappers.@declare_library_product(libmpfr, "libmpfr.so.6")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libmpfr,
        "lib/libmpfr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
