# Autogenerated wrapper script for MPFR_jll for x86_64-w64-mingw32
export libmpfr

using GMP_jll
JLLWrappers.@generate_wrapper_header("MPFR")
JLLWrappers.@declare_library_product(libmpfr, "libmpfr-6.dll")
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libmpfr,
        "bin\\libmpfr-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
